import About from "@/components/About/About";
import Archive from "@/components/Archive/Archive";
import Client from "@/components/Client/Client";
import Contact from "@/components/Contact/Contact";
import Hero from "@/components/Hero/Hero";
import Showreel from "@/components/Showreel/Showreel";
import Work from "@/components/Work/Work";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Star Of Life</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Showreel />
      <Work />
      <Archive />
      <Client />
      <About />
      <Contact />
      <div style={{ height: "100vh" }} />
    </>
  );
}
